### ISSUE TITLE
Crash on load empty custom profile

### ISSUE THREAD

**Issue by shuvashish76** [ljmc2000/NoiseLooper#2]
### Steps to produce:

1. Fresh install the app or don't use "save custom profile"
2. Click on "load custom profile" > pick nothing > Load
3. App crashes

### Logs:

```
FATAL EXCEPTION: main
Process: ie.delilahsthings.soothingloop, PID: 6964
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at ie.delilahsthings.soothingloop.SaveLoadDialog.onClick(SaveLoadDialog.java:36)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Device details:

Android: 9
Device model: Lenovo TB-8704X
App version: 1.0.4

**Comment by ljmc2000** [comment]
Resolved by commit a4dffb928a45772a3e6fbd824c4dc8ccc77b5342
